# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'screen-stream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for screen-stream
  pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'

end

target 'screen-stream-watch' do
  pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'
end

target 'screen-stream-swift' do
  use_frameworks!
  pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'
end

target 'screen-stream-watch-swift' do
  use_frameworks!
  pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'
end
